### PR TITLE
add ruby style ago and fromNow

### PR DESCRIPTION
**Pull request by ConfusedVorlon**
allows 1.hour.fromNow or 2.days.ago

### CODE REVIEW

**Comment by dreymonde** [comment]
Hi! Thanks for your time and contribution. While this additions can definitely be helpful, I don’t feel like they fits with Swift nicely, and the goal of **Time** was never to follow all the Ruby syntax precisely. I won’t merge this PR, but I highly appreciate your interest!

**Comment by ConfusedVorlon** [comment]
That's a shame - it's definitely something I'm using.

I'm not advocating following ruby syntax for the sake of it (though Swift certainly feels a lot closer to ruby than objC ever did). 

In this specific case though - it seems like a useful function that fits naturally in the syntax you added and doesn't have any downsides that I can see...

Is there a more 'swifty' approach that you would accept? I'd certainly rather figure out something that you would pull, rather than maintain my own fork.

**Comment by dreymonde** [comment]
@ConfusedVorlon sorry for the delay.

Personally, I’m absolutely fine with `Date() + 2.hours`. It reads naturally for every context (one of the problems with `fromNow`/`ago` is that it’s tied heavily to English).

For me the reason I don’t like `fromNow`/`ago` is that it has an invisible and inescapable dependency with a side effect.

**Comment by ConfusedVorlon** [comment]
fair enough - thanks for responding

**Pull request closed without merging**
